### ISSUE TITLE
Dose this project provide label files, such as voc or coco?

### ISSUE THREAD

**Issue by April4lu** [VISWESWARAN1998/Fire-Detection-Dataset#2]

**Comment by VISWESWARAN1998** [comment]
For now I only collected this data for classification purpose so those are separated into two directories one with fire and the other with no fire in it. There are no annotations however for now, Sorry! May be in the near future there might be some annotations on it.

**Comment by April4lu** [comment]
> For now I only collected this data for classification purpose so those are separated into two directories one with fire and the other with no fire in it. There are no annotations however for now, Sorry! May be in the near future there might be some annotations on it.

Thank you for your reply.

**Comment by VISWESWARAN1998** [comment]
You are welcome!

Thanks and Regards,
Visweswaran N
